name: Auto Merge

on:
  pull_request:
    types: [opened, synchronize]
  status:
    success

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Check if pull request is ready to merge
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const pr = await github.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number
          });
          const isPipelineSuccess = context.payload.state === 'success'; // Check pipeline status
          const isMergeable = pr.data.mergeable === true; // Check if PR is mergeable
          if (isPipelineSuccess && isMergeable) {
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
          }
